server:
  port:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test
  jpa:
    show-sql: true



